server:
  port: 8080  # Puerto en el que se ejecuta el gateway

spring:
  cloud:
    gateway:
      routes:
        - id: Empleados
          uri: http://localhost:8082/api/empleados
          predicates:
            - Path=/empleados/**
          filters:
            - StripPrefix=1

        - id: Pruebas
          uri: http://localhost:8081/api/pruebas
          predicates:
            - Path=/pruebas/**
          filters:
            - StripPrefix=1
