server:
  port: 8080  # El puerto en el que se ejecutará el gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: pruebas-service
          uri: http://localhost:8081  # URL del servicio Pruebas
          predicates:
            - Path=/api/pruebas/**  # Rutas para el servicio Pruebas
        - id: interesados
          uri: http://localhost:8081  # URL del servicio Interesados (en el microservicio Pruebas)
          predicates:
            - Path=/api/interesados/**  # Rutas para el servicio Interesados
        - id: empleados
          uri: http://localhost:8082  # URL del servicio Empleados
          predicates:
            - Path=/api/empleados/**  # Rutas para el servicio Empleados
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"