server:
  port: 8080  # El puerto en el que se ejecutará el gateway

spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://labsys.frc.utn.edu.ar/aim/realms/backend-tps
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: pruebas-service
          uri: http://localhost:8081  # URL del servicio Pruebas
          predicates:
            - Path=/api/pruebas/**  # Rutas para el servicio Pruebas

        - id: interesados
          uri: http://localhost:8081  # URL del servicio Interesados (en el microservicio Pruebas)
          predicates:
            - Path=/api/interesados/**  # Rutas para el servicio Interesados

        - id: marcas
          uri: http://localhost:8081  # URL del servicio Interesados (en el microservicio Pruebas)
          predicates:
            - Path=/api/marcas/**  # Rutas para el servicio Interesados

        - id: modelos
          uri: http://localhost:8081  # URL del servicio Interesados (en el microservicio Pruebas)
          predicates:
            - Path=/api/modelos/**  # Rutas para el servicio Interesados

        - id: notificaciones
          uri: http://localhost:8081  # URL del servicio Notificaciones (en el microservicio Pruebas)
          predicates:
            - Path=/api/notificaciones/**  # Rutas para el servicio Notificaciones

        - id: posiciones
          uri: http://localhost:8081  # URL del servicio Posiciones (en el microservicio Pruebas)
          predicates:
            - Path=/api/posiciones/**  # Rutas para el servicio Posiciones

        - id: servicio
          uri: http://localhost:8081  # URL del servicio de Información/Configuración (en el microservicio Pruebas)
          predicates:
            - Path=/api/informacion/**  # Rutas para el servicio de Información/Configuración

        - id: empleados
          uri: http://localhost:8082  # URL del servicio Empleados
          predicates:
            - Path=/api/empleados/**  # Rutas para el servicio Empleados

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"